version: '3'
services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
    volumes:
      - .:/project
      # - ./data/it.uniparthenope.meteo.data/opendap:/project/opendap
    ports:
      - '50000:50000'
    depends_on:
      - db
      - memcached
    links:
      - db
      - memcached
  db:
    image: "mongo"
    volumes:
      - ./backup_db:/backup_db
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    ports:
      - '27017:27017'
    restart: always
    # command: mongod --port 27018
    # if you want create a user in to database
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=pass # to set
  memcached:
    image: "memcached:1.6.21"
    ports:
      - '11211:11211'
    command: memcached

